[package]
name = "backbone"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.1"

[dependencies.pyo3]
version = "0.19.2"
features = ["abi3-py37"]
